version: '3'

networks:
  indy-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IDC_API_SUBNET-172.16.0.0/24}

services:
  pool:
    image: idchain/testpool
    ports:
      - ${IDC_POOL_PORTS-9701-9708}:${IDC_POOL_PORTS-9701-9708}
    environment:
      - IDC_POOL_NAME
      - IDC_POOL_IP
      - IDC_PORT_START
    networks:
      indy-network:
        ipv4_address: ${IDC_POOL_IP}

  mongodb:
    image: mongo:4
    command: --smallfiles
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${IDC_API_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${IDC_API_DB_PASSWORD}
    networks:
      - indy-network

  schemac:
    image: idchain/schemacompiler
    environment:
      - SCHEMA_COMP_HOST
      - SCHEMA_COMP_PORT
    networks:
      indy-network:
        ipv4_address: ${SCHEMA_COMP_HOST}

  api:
    build:
      context: .
    image: idchain/api
    container_name: idchain-api
    environment:
      - IDC_API_HOST
      - IDC_API_PORT
      - IDC_API_DOMAIN_PROTOCOL
      - IDC_API_DOMAIN_HOST
      - IDC_API_DOMAIN_PORT
      - IDC_API_NYM_ALWAYS
      - IDC_API_JWT_SECRET
      - IDC_API_DB_HOST
      - IDC_API_DB_PORT
      - IDC_API_DB_USER
      - IDC_API_DB_PASSWORD
      - IDC_API_SALTROUNDS
      - IDC_POOL_IP
      - IDC_POOL_NAME
      - IDC_API_GENESIS_TXN
      - IDC_API_LOG_LEVEL
      - RUST_LOG
      - SCHEMA_COMP_HOST
      - SCHEMA_COMP_PORT
    ports:
      - ${IDC_API_PORT}:${IDC_API_PORT}
    depends_on:
      - mongodb
      - pool
      - schemac
    networks:
      indy-network:
        ipv4_address: ${IDC_API_HOST}
