version: '3'
services:
  pool:
    build:
      context: .
      dockerfile: indy-pool.dockerfile
      args:
        - POOL_IP=${APP_HOST}
    ports:
      - 9701-9708:9701-9708
    network_mode: host

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles
    network_mode: host

  api:
    build:
      context: .
    container_name: idchain-api
    image: indy-api:latest
    environment:
      - GENESIS_TXN=pool_transactions_genesis.docker-compose
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - pool
    network_mode: host
